
/*
 * Copyright © 2016, Malyshev Vladislav,  thestrangesquirrel@gmail.com. This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License. To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
 */

package net.squirrel.poshtar.server.post.intime.sh.reality.in_time.api20;

import net.squirrel.poshtar.server.post.intime.sh.reality.in_time.integration.ReserveNumbersRequest;
import net.squirrel.poshtar.server.post.intime.ua.intime.inr.in_time.integration20.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "API20PortType", targetNamespace = "http://www.reality.sh/in-time/Api20")
@XmlSeeAlso({
        ObjectFactory.class,
    net.squirrel.poshtar.server.post.intime.sh.reality.in_time.integration.ObjectFactory.class,
    net.squirrel.poshtar.server.post.intime.ua.intime.inr.in_time.integration20.ObjectFactory.class
})
public interface API20PortType {


    /**
     * 
     * @param addRequest
     * @return
     *     returns AddTTNRespond
     */
    @WebMethod(operationName = "AddTTN", action = "http://www.reality.sh/in-time/Api20#API20:AddTTN")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "AddTTN", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "AddTTN")
    @ResponseWrapper(localName = "AddTTNResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "AddTTNResponse")
    public AddTTNRespond addTTN(
            @WebParam(name = "AddRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    AddTTNRequest addRequest);

    /**
     * 
     * @param calculateRequest
     * @return
     *     returns CalculateRespond
     */
    @WebMethod(operationName = "CalculateTTN", action = "http://www.reality.sh/in-time/Api20#API20:CalculateTTN")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "CalculateTTN", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "CalculateTTN")
    @ResponseWrapper(localName = "CalculateTTNResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "CalculateTTNResponse")
    public CalculateRespond calculateTTN(
            @WebParam(name = "CalculateRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    CalculateRequest calculateRequest);

    /**
     * 
     * @param generateLabelsRequest
     * @return
     *     returns PrintLabelsRespond
     */
    @WebMethod(operationName = "PrintLabel", action = "http://www.reality.sh/in-time/Api20#API20:PrintLabel")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "PrintLabel", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "PrintLabel")
    @ResponseWrapper(localName = "PrintLabelResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "PrintLabelResponse")
    public PrintLabelsRespond printLabel(
            @WebParam(name = "GenerateLabelsRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    PrintLabelsRequest generateLabelsRequest);

    /**
     * 
     * @param printTTNRequest
     * @return
     *     returns PrintTTNRespond
     */
    @WebMethod(operationName = "PrintTTN", action = "http://www.reality.sh/in-time/Api20#API20:PrintTTN")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "PrintTTN", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "PrintTTN")
    @ResponseWrapper(localName = "PrintTTNResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "PrintTTNResponse")
    public PrintTTNRespond printTTN(
            @WebParam(name = "PrintTTNRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    PrintTTNRequest printTTNRequest);

    /**
     * 
     * @param reserveNumbersRequest
     * @return
     *     returns ReserveNumbersRespond
     */
    @WebMethod(operationName = "ReserveNumbers", action = "http://www.reality.sh/in-time/Api20#API20:ReserveNumbers")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "ReserveNumbers", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "ReserveNumbers")
    @ResponseWrapper(localName = "ReserveNumbersResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "ReserveNumbersResponse")
    public ReserveNumbersRespond reserveNumbers(
            @WebParam(name = "ReserveNumbersRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    ReserveNumbersRequest reserveNumbersRequest);

    /**
     * 
     * @param deleteRequest
     * @return
     *     returns DeleteTTNRespond
     */
    @WebMethod(operationName = "DeleteTTN", action = "http://www.reality.sh/in-time/Api20#API20:DeleteTTN")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "DeleteTTN", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "DeleteTTN")
    @ResponseWrapper(localName = "DeleteTTNResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "DeleteTTNResponse")
    public DeleteTTNRespond deleteTTN(
            @WebParam(name = "DeleteRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    DeleteTTNRequest deleteRequest);

    /**
     * 
     * @param printTTNExtRequest
     * @return
     *     returns PrintTTNExtRespond
     */
    @WebMethod(operationName = "PrintTTNExt", action = "http://www.reality.sh/in-time/Api20#API20:PrintTTNExt")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "PrintTTNExt", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "PrintTTNExt")
    @ResponseWrapper(localName = "PrintTTNExtResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "PrintTTNExtResponse")
    public PrintTTNExtRespond printTTNExt(
            @WebParam(name = "PrintTTNExtRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    PrintTTNExtRequest printTTNExtRequest);

    /**
     * 
     * @param generateLabelsExtRequest
     * @return
     *     returns PrintLabelsExtRespond
     */
    @WebMethod(operationName = "PrintLabelsExt", action = "http://www.reality.sh/in-time/Api20#API20:PrintLabelsExt")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "PrintLabelsExt", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "PrintLabelsExt")
    @ResponseWrapper(localName = "PrintLabelsExtResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "PrintLabelsExtResponse")
    public PrintLabelsExtRespond printLabelsExt(
            @WebParam(name = "GenerateLabelsExtRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    PrintLabelsExtRequest generateLabelsExtRequest);

    /**
     * 
     * @param dayOfDeliveryRequest
     * @return
     *     returns DayOfDeliveryRespond
     */
    @WebMethod(operationName = "DeliveryDay", action = "http://www.reality.sh/in-time/Api20#API20:DeliveryDay")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "DeliveryDay", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "DeliveryDay")
    @ResponseWrapper(localName = "DeliveryDayResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "DeliveryDayResponse")
    public DayOfDeliveryRespond deliveryDay(
            @WebParam(name = "DayOfDeliveryRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    DayOfDeliveryRequest dayOfDeliveryRequest);

    /**
     * 
     * @param allCatalogRequest
     * @return
     *     returns AllCatalogRespond
     */
    @WebMethod(operationName = "AllCatalog", action = "http://www.reality.sh/in-time/Api20#API20:AllCatalog")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "AllCatalog", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "AllCatalog")
    @ResponseWrapper(localName = "AllCatalogResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "AllCatalogResponse")
    public AllCatalogRespond allCatalog(
            @WebParam(name = "AllCatalogRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    AllCatalogRequest allCatalogRequest);

    /**
     * 
     * @param catalogListRequest
     * @return
     *     returns CatalogListRespond
     */
    @WebMethod(operationName = "CatalogList", action = "http://www.reality.sh/in-time/Api20#API20:CatalogList")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "CatalogList", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "CatalogList")
    @ResponseWrapper(localName = "CatalogListResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "CatalogListResponse")
    public CatalogListRespond catalogList(
            @WebParam(name = "CatalogListRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    CatalogListRequest catalogListRequest);

    /**
     * 
     * @param listTTNRequest
     * @return
     *     returns ListTTNRespond
     */
    @WebMethod(operationName = "ListTTN", action = "http://www.reality.sh/in-time/Api20#API20:ListTTN")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "ListTTN", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "ListTTN")
    @ResponseWrapper(localName = "ListTTNResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "ListTTNResponse")
    public ListTTNRespond listTTN(
            @WebParam(name = "ListTTNRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    ListTTNRequest listTTNRequest);

    /**
     * 
     * @param transferCargoRequest
     * @return
     *     returns TransferCargoRespond
     */
    @WebMethod(operationName = "TransferCargo", action = "http://www.reality.sh/in-time/Api20#API20:TransferCargo")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "TransferCargo", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "TransferCargo")
    @ResponseWrapper(localName = "TransferCargoResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "TransferCargoResponse")
    public TransferCargoRespond transferCargo(
            @WebParam(name = "TransferCargoRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    TransferCargoRequest transferCargoRequest);

    /**
     * 
     * @param transferCargoListRequest
     * @return
     *     returns TransferCargoListRespond
     */
    @WebMethod(operationName = "TransferCargoList", action = "http://www.reality.sh/in-time/Api20#API20:TransferCargoList")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "TransferCargoList", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "TransferCargoList")
    @ResponseWrapper(localName = "TransferCargoListResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "TransferCargoListResponse")
    public TransferCargoListRespond transferCargoList(
            @WebParam(name = "TransferCargoListRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    TransferCargoListRequest transferCargoListRequest);

    /**
     * 
     * @param checkoutRequest
     * @return
     *     returns CheckoutRespond
     */
    @WebMethod(operationName = "Checkout", action = "http://www.reality.sh/in-time/Api20#API20:Checkout")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "Checkout", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "Checkout")
    @ResponseWrapper(localName = "CheckoutResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "CheckoutResponse")
    public CheckoutRespond checkout(
            @WebParam(name = "CheckoutRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    CheckoutRequest checkoutRequest);

    /**
     * 
     * @param creatingReferenceRequest
     * @return
     *     returns CreatingReferenceRespond
     */
    @WebMethod(operationName = "Change", action = "http://www.reality.sh/in-time/Api20#API20:Change")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "Change", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "Change")
    @ResponseWrapper(localName = "ChangeResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "ChangeResponse")
    public CreatingReferenceRespond change(
            @WebParam(name = "CreatingReferenceRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    CreatingReferenceRequest creatingReferenceRequest);

    /**
     * 
     * @param referenceListRequest
     * @return
     *     returns ReferenceListRespond
     */
    @WebMethod(operationName = "ChangeTTNList", action = "http://www.reality.sh/in-time/Api20#API20:ChangeTTNList")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "ChangeTTNList", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "ChangeTTNList")
    @ResponseWrapper(localName = "ChangeTTNListResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "ChangeTTNListResponse")
    public ReferenceListRespond changeTTNList(
            @WebParam(name = "ReferenceListRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    ReferenceListRequest referenceListRequest);

    /**
     * 
     * @param actOfReconciliationRequest
     * @return
     *     returns ActOfReconciliationRespond
     */
    @WebMethod(operationName = "ActOfReconciliation", action = "http://www.reality.sh/in-time/Api20#API20:ActOfReconciliation")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "ActOfReconciliation", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "ActOfReconciliation")
    @ResponseWrapper(localName = "ActOfReconciliationResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "ActOfReconciliationResponse")
    public ActOfReconciliationRespond actOfReconciliation(
            @WebParam(name = "ActOfReconciliationRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    ActOfReconciliationRequest actOfReconciliationRequest);

    /**
     * 
     * @param infoTTNRequest
     * @return
     *     returns InfoTTNRespond
     */
    @WebMethod(operationName = "InfoTTN", action = "http://www.reality.sh/in-time/Api20#API20:InfoTTN")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "InfoTTN", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "InfoTTN")
    @ResponseWrapper(localName = "InfoTTNResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "InfoTTNResponse")
    public InfoTTNRespond infoTTN(
            @WebParam(name = "InfoTTNRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    InfoTTNRequest infoTTNRequest);

    /**
     * 
     * @param transferCarcoViewRequest
     * @return
     *     returns TransferCargoViewRespond
     */
    @WebMethod(operationName = "TransferCargoView", action = "http://www.reality.sh/in-time/Api20#API20:TransferCargoView")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "TransferCargoView", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "TransferCargoView")
    @ResponseWrapper(localName = "TransferCargoViewResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "TransferCargoViewResponse")
    public TransferCargoViewRespond transferCargoView(
            @WebParam(name = "TransferCarcoViewRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    TransferCargoViewRequest transferCarcoViewRequest);

    /**
     * 
     * @param claimRequest
     * @return
     *     returns ClaimRespond
     */
    @WebMethod(operationName = "Claim", action = "http://www.reality.sh/in-time/Api20#API20:Claim")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "Claim", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "Claim")
    @ResponseWrapper(localName = "ClaimResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "ClaimResponse")
    public ClaimRespond claim(
            @WebParam(name = "ClaimRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    ClaimRequest claimRequest);

    /**
     * 
     * @param userWarningRequest
     * @return
     *     returns UserWarningListRespond
     */
    @WebMethod(operationName = "UserWarning", action = "http://www.reality.sh/in-time/Api20#API20:UserWarning")
    @WebResult(targetNamespace = "http://www.reality.sh/in-time/Api20")
    @RequestWrapper(localName = "UserWarning", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "UserWarning")
    @ResponseWrapper(localName = "UserWarningResponse", targetNamespace = "http://www.reality.sh/in-time/Api20", className = "UserWarningResponse")
    public UserWarningListRespond userWarning(
            @WebParam(name = "UserWarningRequest", targetNamespace = "http://www.reality.sh/in-time/Api20")
                    UserWarningListRequest userWarningRequest);

}
